name: Run Python Script Hourly

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run main.py
        run: python main.py
